name: CI
on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  windows:
    runs-on: windows-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: clone gecko
        run: git clone https://github.com/mozilla/gecko-dev --depth=1
      - name: Build
        run: |
          mkdir firefox
          cd firefox/
          wget -q https://hg.mozilla.org/mozilla-central/raw-file/default/python/mozboot/bin/bootstrap.py -O bootstrap.py
          python bootstrap.py
      
