name: CI
on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  windows:
    runs-on: windows-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          repository: mozilla/gecko-dev
      - name: Install mozilla-build
        run: |
          Invoke-WebRequest -Uri https://archive.mozilla.org/pub/mozilla.org/mozilla-build/mozilla-build-latest.zip -OutFile mozilla-build.zip
          Expand-Archive -Path mozilla-build.zip -DestinationPath C:/mozilla-build
      - name: Bootstrap
        run: |
          #New-Item "../mozilla-source" -ItemType Directory
          #cd ../mozilla-source

          #Invoke-WebRequest https://hg.mozilla.org/mozilla-central/raw-file/default/python/mozboot/bin/bootstrap.py -OutFile bootstrap.py
          #python3 bootstrap.py --no-interactive --application-choice browser

          #cd ../gecko-dev

          ./mach.ps1 --no-interactive bootstrap --application-choice browser
