name: CI
on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  windows:
    runs-on: windows-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: clone gecko
        run: git clone https://github.com/mozilla/gecko-dev --depth=1

      - name: Install Firefox build dependencies
        run: |
          python -m pip install -r ./mach/env/requirements.txt
          ./mach bootstrap --no-interactive --application-choice=browser

      - name: Build Firefox
        run: |
          cd gecko-dev
          ./mach build
